import type { ProductService } from "../types/product"

export const PIERCING_CATEGORIES = [
  { id: "nose", name: "Nariz", icon: "nose" },
  { id: "lips", name: "Labios", icon: "lips" },
  { id: "ear", name: "Oreja", icon: "ear" },
  { id: "eyebrow", name: "Ceja", icon: "eyebrow" },
  { id: "tongue", name: "Lengua", icon: "tongue" },
]

export const JEWELRY_CATEGORIES = [
  { id: "rings", name: "Anillos", icon: "circle" },
  { id: "necklaces", name: "Collares", icon: "necklace" },
  { id: "sets", name: "Sets", icon: "rings" },
  { id: "earrings", name: "Aretes", icon: "earrings" },
  { id: "horseshoe", name: "Herradura", icon: "horseshoe" },
]

export const PIERCING_SERVICES: ProductService[] = [
  {
    id: "nostrile",
    title: "Nostrile",
    description:
      "Dale a tu perfil un brillo fresco con nuestro servicio de piercing nostril. En una sesión de pocos minutos creamos una perforación limpia y precisa, guiándote en cada paso para que disfrutes el resultado.",
    price: 15000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [
      { id: "main", src: "/images/nostril-main.png", alt: "Piercing nostrile", type: "main" },
      { id: "thumb1", src: "/images/nostril-thumb-1.png", alt: "Vista lateral", type: "result" },
      { id: "thumb2", src: "/images/nostril-thumb-2.png", alt: "Vista frontal", type: "result" },
      { id: "thumb3", src: "/images/nostril-thumb-3.png", alt: "Joyería", type: "product" },
    ],
    categoryId: "nose",
  },
  {
    id: "smiley",
    title: "Smiley",
    description:
      "Un piercing discreto y único que se revela con tu sonrisa. Perfecto para quienes buscan algo especial y diferente.",
    price: 30000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Piercing smiley", type: "main" }],
    categoryId: "lips",
  },
  {
    id: "septum",
    title: "Septum",
    description: "Un clásico atemporal que aporta personalidad y estilo. Versátil y elegante para cualquier ocasión.",
    price: 18000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Piercing septum", type: "main" }],
    categoryId: "nose",
  },
  {
    id: "industrial",
    title: "Industrial",
    description:
      "Un piercing llamativo y moderno que conecta dos puntos del oído con una barra recta. Para los más atrevidos.",
    price: 22000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Piercing industrial", type: "main" }],
    categoryId: "ear",
  },
  {
    id: "labret",
    title: "Labret",
    description:
      "Elegante y versátil, el piercing labret es perfecto para complementar tu estilo personal con sutileza.",
    price: 15000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Piercing labret", type: "main" }],
    categoryId: "lips",
  },
  {
    id: "navel",
    title: "Navel",
    description: "Un clásico que nunca pasa de moda. Perfecto para mostrar tu personalidad y estilo único.",
    price: 7000,
    originalPrice: 15000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Piercing navel", type: "main" }],
    categoryId: "body",
    isOnSale: true,
  },
  {
    id: "ceja",
    title: "Ceja",
    description: "Un piercing que enmarca tu mirada y añade un toque rebelde y sofisticado a tu expresión.",
    price: 40000,
    currency: "$",
    category: "piercing",
    features: ["Evaluación personalizada", "Joyería de acero", "Acompañamiento post-servicio"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Piercing ceja", type: "main" }],
    categoryId: "eyebrow",
  },
]

export const JEWELRY_PRODUCTS: ProductService[] = [
  {
    id: "anillo-anna",
    title: "Anillo Anna",
    description: "Elegante anillo con cristales que aporta sofisticación y brillo a cualquier look.",
    price: 15000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Cristales de alta calidad", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Anillo Anna", type: "main" }],
    categoryId: "rings",
  },
  {
    id: "set-anillos",
    title: "Set de Anillos",
    description: "Conjunto de anillos variados para crear combinaciones únicas y personalizadas.",
    price: 30000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Diseños variados", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Set de anillos", type: "main" }],
    categoryId: "sets",
  },
  {
    id: "anillo-snake",
    title: "Anillo Snake",
    description: "Diseño serpentino único que añade un toque místico y elegante a tu colección.",
    price: 18000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Diseño exclusivo", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Anillo Snake", type: "main" }],
    categoryId: "rings",
    isNew: true,
  },
  {
    id: "anillo-waves",
    title: "Anillo Waves",
    description: "Diseño ondulado que captura la fluidez y movimiento del agua en una pieza única.",
    price: 22000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Diseño ondulado", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Anillo Waves", type: "main" }],
    categoryId: "rings",
  },
  {
    id: "anillo-moon",
    title: "Anillo Moon",
    description: "Inspirado en las fases lunares, este anillo aporta misticismo y elegancia a tu estilo.",
    price: 15000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Diseño lunar", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Anillo Moon", type: "main" }],
    categoryId: "rings",
  },
  {
    id: "anillo-summer",
    title: "Anillo Summer",
    description: "Colores vibrantes que capturan la esencia del verano en una pieza radiante.",
    price: 7000,
    originalPrice: 15000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Cristales coloridos", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Anillo Summer", type: "main" }],
    categoryId: "rings",
    isOnSale: true,
  },
  {
    id: "par-anillos",
    title: "Par de Anillos",
    description: "Conjunto de anillos a juego, perfectos para crear looks coordinados y armoniosos.",
    price: 40000,
    currency: "$",
    category: "jewelry",
    features: ["Acero quirúrgico", "Diseño a juego", "Hipoalergénico"],
    images: [{ id: "main", src: "/placeholder.svg?height=400&width=400", alt: "Par de anillos", type: "main" }],
    categoryId: "rings",
  },
]
